### ISSUE TITLE
[FEATURE] add "All" to glossary letter list

### ISSUE THREAD

**Issue by erredeco** [jweiland-net/glossary2#10]
This is a feature request: is it possible to have a "all" link in the Glossary letter list that cancels the filter?

**Comment by froemken** [comment]
Nice idea. We have implemented that for a customer already. We think it would be good to de-/activate that in FlexForm/TypoScript. Default off, to be compatible with all other installations out there.

Stefan

**Comment by froemken** [comment]
I'm just working on a version 3.0.0. In current PullRequest I have added that Feature already.
