### ISSUE TITLE
[DOC] add documentation for routeEnhancers 

### ISSUE THREAD

**Issue by erredeco** [jweiland-net/glossary2#11]
Please add documentation (or a sample config) about how to configure routeEnhancers to have nice urls on TYPO3 9.5 and higher.
A-Z filter and pagination should be taken into account.

Thanks!

**Comment by froemken** [comment]
Hello @erredeco 

I have added these information in documentation of new version 3.0.1

Thank you

Stefan

**Comment by erredeco** [comment]
I added the config in your documentation to my yaml file, and I have a couple of question/issues:

1- would it be possible to remove the cHash parameter
2- the pagination doesn't seem to work with the A-Z filter. I'll explain better with this example

- write a lot of terms that begins with "A" and shorten the pagination to make it easier, for example: `plugin.tx_glossary2.settings.pageBrowser.itemsPerPage = 3`
- write some terms with different letters
- put the plugin on a page, with pagination AND A-Z filter active.
- visit the frontend

1) if you click on the "A" letter the filter kicks in and only "A" terms are shown, this is also visible on the pagination because it will contain less pages
2) Now click on page two 

**expected result:** 
you navigate to the page 2 of the pagination, with the letter filter still active

actual result
**the A-Z** filter is resetted and you see all the terms again

This is actually an effect of the routeenhancers, because without any configuration, everything works as expected.

Do you want me to open a different issue for that? Thanks !

**Comment by froemken** [comment]
Hello @erredeco 

I have just released version 5.0.0. I have implemented a new paginator and updated the documentation for RouteEnhancers. With new config I don't found any cHash anymore.

Nice greetings

Stefan
