### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by p380** [jweiland-net/glossary2#2]
Is there a search engine in the plan?

**Comment by froemken** [comment]
Good Morning @p380 

a search for the glossary2? Sorry, currently we don't have this at our schedule. We are using Solr and have an index configuration for the glossary table. Else you can use ke_search, where you also can configure individual tables for indexing.
So, why do you need a plugin related individual search for glossary2?

Nice greetings

Stefan

**Comment by froemken** [comment]
No comment within the last months. I'm closing this issue. Feel free to reopen it.

Stefan
