### ISSUE TITLE
TYPO3 12 Version 

### ISSUE THREAD

**Issue by Avishayhz** [jweiland-net/glossary2#63]
Would you make a TYPO3 12 compatible version?

**Comment by jweiland** [comment]
Yes, we will upgrade the glossary2 extension for v12, however we don't have an exact timeframe for that.

**Comment by Avishayhz** [comment]
I have a working instance of the extension where i used rector and upgraded some breaking changes. can i submit it ?

**Comment by jweiland** [comment]
Sure, you are very welcome to submit a pull request. However, it can take a week or so until the developer of the extension can review it.
