### ISSUE TITLE
Alternative sort field

### ISSUE THREAD

**Issue by Epoche-Napoleon** [jweiland-net/glossary2#9]
Will it be possible to add an alternative sort field to EXT: in a next release? 

To reproduce extensive reference books it is necessary to have an alternative sort field in addition to the title.

**Comment by froemken** [comment]
Hello @Epoche-Napoleon 

to add additional fields please use EXT:extender. So the only problem is, how to add an additional order by? I can implement a new hook to Repository where you can modify the query. Would that be OK for you?

Stefan

**Comment by froemken** [comment]
Hello @Epoche-Napoleon 

I have modified Repository and added a hook to modify the extbase query. I have tested it and it works good. So now it should not be a problem anymore to extend glossary2 with EXT:extender and apply your own orderings.

Stefan
